{{- $self := . -}}
{{- range .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ $self.Values.serviceAccountName }}-{{ . }}
  labels:
    app.kubernetes.io/managed-by: {{$self.Release.Service | quote }}
    app.kubernetes.io/instance: {{$self.Release.Name | quote }}
    helm.sh/chart: "{{$self.Chart.Name}}-{{$self.Chart.Version}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ $self.Values.serviceAccountName }}
  namespace: {{ . | quote }}
{{- end }}
