apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "aws-ecr.fullname" . }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2  
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          name: {{ include "aws-ecr.fullname" . }}
          labels:
            app.kubernetes.io/managed-by: {{.Release.Service | quote }}
            app.kubernetes.io/instance: {{.Release.Name | quote }}
            helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        spec:
          serviceAccountName: {{ .Values.serviceAccountName }}
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
          {{- include "aws-ecr.container-spec" . | nindent 10 }}
